In [1]:
#Question 1

import numpy as np


arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))




arr = list(arr)
print(type(arr))
print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>
[1, 2, 3, 4, 5]


In [4]:
#Question 2

import numpy as np 


num_array = np.array([[55,25,15],
                   [30,44,2],
                   [11,45,77]])


print("numpy matrix is:")
print(num_array)


trace = np.trace(num_array)


print("/n Trace of given 3x3 Matrix:")

print(trace)

numpy matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]
/n Trace of given 3x3 Matrix:
176


In [5]:
#Question 3. DONT GRADE ON THIS! THIS IS COPY AND PASTED FOR LEARNING PURPOSES
# Importing Library
import numpy as np

# creating 2d array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating mean across Rows
row_mean = np.mean(arr, axis=1)

row1_mean = row_mean[0]
print("Mean of Row 1 is", row1_mean)

row2_mean = row_mean[1]
print("Mean of Row 2 is", row2_mean)

row3_mean = row_mean[2]
print("Mean of Row 3 is", row3_mean)


# Calculating mean across Columns
column_mean = np.mean(arr, axis=0)

column1_mean = column_mean[0]
print("Mean of column 1 is", column1_mean)

column2_mean = column_mean[1]
print("Mean of column 2 is", column2_mean)

column3_mean = column_mean[2]
print("Mean of column 3 is", column3_mean)


Mean of Row 1 is 2.0
Mean of Row 2 is 5.0
Mean of Row 3 is 8.0
Mean of column 1 is 4.0
Mean of column 2 is 5.0
Mean of column 3 is 6.0
